export const GET_USERS = "GET_USERS";
export const CREATE_USERS = "CREATE_USERS";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const UPDATE_USERS = "UPDATE_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION";
export const OTP_VERIFICATION = "OTP_VERIFICATION";
export const LOGIN = "LOGIN";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const CART_PRODUCTS = "CART_PRODUCTS";
export const GET_CARTS = "GET_CARTS";
export const POST_CHECKOUT = "POST_CHECKOUT";